openapi: 3.0.0
info:
  title: User Service API
  description: API for managing users
  version: 1.0.0

paths:
  /users:
    post:
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
  /users/{userId}:
    get:
      operationId: getUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUserRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'

components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - username
        - email
        - tags
    CreateUserResponse:
      type: object
      properties:
        userID:
          type: string
        success:
          type: boolean
        errorCode:
          type: integer
          format: int64
      required:
        - userID
        - success
        - errorCode
    GetUserRequest:
      type: object
      properties:
        userID:
          type: string
      required:
        - userID
    GetUserResponse:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        found:
          type: boolean
      required:
        - username
        - email
        - found
